---
version: "3"

services:

  k9s:
    container_name: "k9s"
    build: .
    restart: always
    volumes:
      - gcloud-secrets:/root/.config/gcloud
      
volumes:
  gcloud-secrets:
    external: true